spring:
  cloud:
    config:
      enabled : false
    gateway:
      routes:
        - id: iaa-service
          uri: http://localhost:9001
          predicates:
            - Path=/iaa/**
          filters:
            - RewritePath=/local/(?<path>.*), /${path}
iaa:
  staging-base-url: http://172.19.6.19:8080
  qa-base-url: http://10.3.1.11:8080